# Base Configuration for MECPE-Enhanced
# Base configuration for MECPE conversation-level training

# Data Configuration
data:
  data_root: "data"
  ecf_train_file: "train.txt"
  ecf_dev_file: "dev.txt"
  ecf_test_file: "test.txt"
  meld_root: "data/MELD.Raw"
  ecf_meld_mapping: "data/all_data_pair_ECFvsMELD.txt"
  
  # Text processing
  max_seq_length: 128
  max_doc_length: 75
  max_sen_len: 35  # Max tokens per sentence for Step2
  
  # Step2 specific
  pred_future_cause: true  # Whether to consider future utterances as causes

# Model Configuration  
model:
  # Text encoder (支持base/large自动维度)
  text_model: "roberta-base"  # 可选: roberta-base, roberta-large
  
  # Step2 specific model architecture
  text_embedding_dim: 300  # GloVe embedding dimension
  position_embedding_dim: 50  # Distance and emotion category embedding
  lstm_hidden_size: 100  # BiLSTM hidden size (becomes 200 bidirectional)
  
  # Multimodal features (modern encoders)
  use_video: false  # Whether to use video features
  use_audio: false  # Whether to use audio features  
  freeze_encoders: false  # Whether to freeze pretrained encoder weights
  
  # Modern encoder specifications
  video_model: "facebook/timesformer-base-finetuned-k400"  # TimeSformer
  audio_model: "facebook/wav2vec2-base-960h"  # Wav2Vec2
  
  # Dropout rates (following original TensorFlow)
  word_dropout: 0.5  # keep_prob1  
  final_dropout: 0.0  # keep_prob2 (no dropout - 1.0 means 100% dropout, 0.0 means no dropout)
  video_dropout: 0.5  # keep_prob_v
  audio_dropout: 0.5  # keep_prob_a
  
  # Task-specific
  num_emotions: 7  # neutral, anger, disgust, fear, joy, sadness, surprise
  num_labels: 2    # binary classification
  use_emotion_categories: false  # Whether to use emotion categories in Step2
  
  # Legacy (for Conv compatibility)
  fusion_hidden_size: 256
  fusion_dropout: 0.1

# Training Configuration
training:
  # Conv-level settings
  batch_size: 8 
  learning_rate: 0.00002  # 2e-5 in decimal format
  num_epochs: 1
  warmup_steps: 500
  weight_decay: 0.01
  gradient_clip_val: 1.0
  
  # Pair-level settings (following original TensorFlow)
  pair_batch_size: 100  # Original pair training batch size
  pair_learning_rate: 0.005  # Original pair training learning rate
  pair_num_epochs: 1  # training_iter (测试end_to_end)
  l2_reg: 0.00001  # L2 regularization (shared with Conv)
  
  # Hardware
  device: "auto"  # auto, cuda, cpu
  mixed_precision: true
  
  # Checkpointing
  save_dir: "experiments/checkpoints"
  log_every: 50
  eval_every: 500

# Experiment Configuration
experiment:
  name: "mecpe_conv"
  seed: 42
  
  # Logging (暂不使用wandb)
  use_wandb: false