# Base Configuration for MECPE-Enhanced
# Simple baseline configuration

# Data Configuration
data:
  data_root: "data"
  ecf_train_file: "train.txt"
  ecf_dev_file: "dev.txt"
  ecf_test_file: "test.txt"
  meld_root: "data/MELD.Raw"
  ecf_meld_mapping: "data/all_data_pair_ECFvsMELD.txt"
  
  # Text processing
  max_seq_length: 128
  max_doc_length: 75

# Model Configuration  
model:
  # Text encoder (支持base/large自动维度)
  text_model: "roberta-base"  # 可选: roberta-base, roberta-large
  
  # Multimodal fusion
  fusion_hidden_size: 256
  fusion_dropout: 0.1
  
  # Task-specific
  num_emotions: 6  # neutral, joy, sadness, anger, surprise, fear
  num_labels: 2    # binary classification

# Training Configuration
training:
  batch_size: 8 
  learning_rate: 0.00002  # 2e-5 in decimal format
  num_epochs: 10
  warmup_steps: 500
  weight_decay: 0.01
  gradient_clip_val: 1.0
  
  # Hardware
  device: "auto"  # auto, cuda, cpu
  mixed_precision: true
  
  # Checkpointing
  save_dir: "experiments/checkpoints"
  log_every: 50
  eval_every: 500

# Experiment Configuration
experiment:
  name: "mecpe_baseline"
  seed: 42
  
  # Logging (暂不使用wandb)
  use_wandb: false